"""empty message

Revision ID: 9511344cdd3c
Revises: fd1d2a65b0fa
Create Date: 2019-09-15 18:01:05.925793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9511344cdd3c'
down_revision = 'fd1d2a65b0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('business_phone', sa.String(length=10), nullable=True))
    op.add_column('client', sa.Column('email_address', sa.String(length=50), nullable=True))
    op.add_column('client', sa.Column('last_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'last_name')
    op.drop_column('client', 'email_address')
    op.drop_column('client', 'business_phone')
    # ### end Alembic commands ###
