"""empty message

Revision ID: e0bd23467f95
Revises: f1e2d6a1d19d
Create Date: 2019-09-18 19:42:29.032606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bd23467f95'
down_revision = 'f1e2d6a1d19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'user_id')
    # ### end Alembic commands ###
