"""empty message

Revision ID: f1e2d6a1d19d
Revises: dd0b2b711c56
Create Date: 2019-09-18 19:39:20.656460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e2d6a1d19d'
down_revision = 'dd0b2b711c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_address', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('password_has', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email_address'), 'user', ['email_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email_address'), table_name='user')
    op.drop_column('user', 'password_has')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email_address')
    # ### end Alembic commands ###
